apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nvidia-dcgm-exporter
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-dcgm-exporter
spec:
  groups:
  - name: dcgm.accelerator.metrics
    interval: 30s
    rules:
    - record: accelerator_gpu_utilization
      expr: DCGM_FI_DEV_GPU_UTIL
      labels:
        vendor: "nvidia"
    
    - record: accelerator_memory_used_bytes
      expr: DCGM_FI_DEV_MEM_COPY_UTIL
      labels:
        vendor: "nvidia"
    
    - record: accelerator_memory_total_bytes
      expr: DCGM_FI_DEV_FB_TOTAL
      labels:
        vendor: "nvidia"
    
    - record: accelerator_power_usage_watts
      expr: DCGM_FI_DEV_POWER_USAGE
      labels:
        vendor: "nvidia"
    
    - record: accelerator_temperature_celcius
      expr: DCGM_FI_DEV_GPU_TEMP
      labels:
        vendor: "nvidia"
    
    - record: accelerator_sm_clock_hertz
      expr: DCGM_FI_DEV_SM_CLOCK
      labels:
        vendor: "nvidia"
    
    - record: accelerator_memory_clock_hertz
      expr: DCGM_FI_DEV_MEM_CLOCK
      labels:
        vendor: "nvidia" 
